### ISSUE TITLE
Policy: Transition Policy FQN indexing to a transaction rather than an unmonitored sideeffect

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#1660]
When the policy service was developed, we made the choice to have the upsert FQN function to act as a side-effect so that we could continue moving quickly. This was not a concern since the fqn reindex was relatively liteweight and could be run at any time.

https://github.com/opentdf/platform/blob/c486712d310bcb6ade364fe5681e8224d0b4217f/service/policy/db/attribute_fqn.go#L22-L31

Since we are introducing transactions with SQLC we should shift this functionality to a transaction to ensure consistency and monitoring.

## Acceptance Criteria
- transition upsertFQN function to utilize a transaction with any attribute changes
  - new namespace
  - new attribute
  - new value
  - unsafe namespace
  - unsafe attribute
  - unsafe value

**Comment by ryanulit** [comment]
The code has changed slightly since this ticket was created.  The `upsertAttrFqn` was removed in PR #1679 with added batching support and usage of the SQLC queries directly.  An `AttrFqnReindex` method remains, but it is only used by a CLI method and the integration testing framework.  This PR will add transaction support to the gRPC service method calls using the SQLC `upsert...` methods directly, as well as the CLI command using `AttrFqnReindex`.
