### ISSUE TITLE
REST HTTP paths have collisions; some paths are not currently usable

### ISSUE THREAD

**Issue by dmihalcik-virtru** [opentdf/platform#313]
Our current use of gRPC Gateway with gorilla.mux results in several name collisions. Notably, the `attributes/namespaces` collides with the `attributes/_` path.

**Comment by jakedoublev** [comment]
All CRUD routes for Get, List, Update, Deactivate/Delete, Create were tested over RESTful gateway for the following policy:
1. attribute namespaces
2. attribute definitions
3. attribute values
4. subject condition sets
5. subject mappings
6. resource mappings

All were found to be accessible and working as expected, with the one exception being Update of resource mappings as POST instead of PATCH which PR  #824 fixes.
