### ISSUE TITLE
Need equivalent of setRule() method for Attribute

### ISSUE THREAD

**Issue by patmantru** [opentdf/platform#434]
As encountered in PLAT-2950 development:

There is no equivalent for setRule() in the protobuf Attribute object

AC:
Ability to use setRule() method, or some equivalent operation

**Comment by biscoe916** [comment]
@jrschumacher @patmantru What's the status of this. Should we close?

**Comment by jrschumacher** [comment]
@biscoe916 We have disabled the ability to update an attribute but prevent rules since this could cause unintended data leakage (all of --> any of). 

We will eventually support unsafe rpcs but that is tracked in another issue. When we do support it I'm not sure if it will be a specific rule or just an unsafe update.
