### ISSUE TITLE
ADR: Entitlement Policy Deployment Model

### ISSUE THREAD

**Issue by ttschampel** [opentdf/platform#472]
# Entitlement Policy Deployment Model

## Context and Problem Statement

The Entitlement Policy (rules, logic, etc.) defines the provisioning of Entitlements to an [Entity](https://github.com/opentdf/platform/blob/main/services/authorization/authorization.proto#L11).  The process of determining what entitlements an Entity may have include the processing of Subject Sets against and Entity, the lookup of an Entity from an authoritative source, the inclusion of customer/deployment specific policy as well as interfacing with external federated Entitlement Services.   

There is also a need to support the injection and verification of an Entitlement Policy from an external source or configuration.

## Decision Drivers

* We don't want to have a high deployment and configuration burden
* We want to reduce friction for Entitlement Policy Authors
* We don't want to re-invent a policy injection, verification and distribution framework
* We want to decouple the platform from Entitlement specific logic and integrations
* We want to support the inclusion of policy and associated integrations dynamically and not known in advance the core platform

## Considered Options

* Custom + Configuration Driven
* OPA Configuration Driven
* OPA Bundle with Custom Built-In Functions

## Decision Outcome

OPA Bundle with Custom Built-In Functions

This option allows for encapsulation of core capabilities as standard Go code while at the same time leveraging an open standard to allow for extensibility, deployment and verification.

![custom_built_in_with_idp](https://github.com/opentdf/platform/assets/641294/2006f920-c4cf-41fa-b8af-5361a655ba6c)

### Custom + Configuration Driven

This option includes the custom development of an extensible, shareable policy framework.

Pros/Cons:

* 🔴 Re-Invent policy language, infrastructure
* 🔴 Re-Invent a verifiable, shareable policy mechanism.

### OPA Configuration Driven

This option uses OPA and Platform configuration to wire up and initialize an OPA runtime; this is current state.  This solution includes Rego implementation of Subject to Entity Mapping interpretation.  OPA plugins are known prior to deployment.

Pros/Cons:

* 🟢 Leverages an existing  and widely used standard (OPA)
* 🔴 Extensibility friction
* 🔴 Coupling to Policy implementation
* 🔴 OPA/Rego learning curve

### OPA Bundle with Custom Built-In Functions

This option uses an OPA Bundle as the deployment unit and consumption into the Entitlement Service.  Core platform OPA built-in functions are used to support common core platform functions.  Standard OPA external data fetching flows  (e.g. Rest Endpoint) are used to support deploy time specific customizations.  This allows for decoupling of entitlement logic; both core and extensions; from the platform as well as supports future requirements of distributed, federating and verifying policy artifacts.  

This option includes the creation and enforcement of the following design guidelines:

* Custom OPA Build-In Functions are to be used for encapsulating complexity in standard Go modules and thereby reducing Rego complexity and friction.   
* IDP specific entity resolution implemented as Services following [OPA's `Pull Data During Evaluation` pattern](https://www.openpolicyagent.org/docs/latest/external-data/#option-5-pull-data-during-evaluation) and integrated through standard OPA http requests.

The implications of this approach:

* The creation of a function to support Subject Set / Entity Representation processing as an OPA Built-In Function.  
* A Keycloak Entity Resolution Service reference implementation.
* Reference implementation Rego policy using subject set and http based entity resolution call-out

Pros/Cons:

* 🟢 Leverages an existing  and widely used standard (OPA)
* 🟢 Leverages a standard packaging, deployment and distribution flow (including verification) 
* 🟢 Extensible and supports decoupling = Support dynamic injection of Policy
* 🟡 OPA/Rego learning curve - mitigated by the use of custom build-in functions to encapsulate complexity in standard Go

**Comment by ttschampel** [comment]
Updated to remove incorrect characterization of the IDP external fetching as Webhook

**Comment by jakedoublev** [comment]
Do we have more documentation on the webhook implementation and the flow with idPs, and/or what the Entity Resolution Service interface looks like?

**Comment by jakedoublev** [comment]
@ttschampel @strantalis @jrschumacher I could be wrong, but if we're mandating a service (webhook, lambda, some kind of deployed layer) between the platform and any idP, that seems like it could be a place to reduce a lot of complexity. Perhaps the lambda could do a deterministic flattening transformation?

The idP value for a given subject might look like:
```json
{
  "user": {
    "name": "username123",
    "org": {
      "id": "d94187fe-629c-4da8-804e-9dc82c1fb4b7",
      "name": "my_org"
    },
    "roles": [
      "role_a",
      "role_b"
    ],
    "groups": [
      "group_1",
      "group_2"
    ],
    "something": {
      "really": {
        "complex": {
          "nested": [
            "here"
          ]
        }
      }
    }
  }
}
```

The webhook could be expected to flatten all values:
```json
{
  "flattened": [
    {
      "key": "user.name",
      "value": "username123"
    },
    {
      "key": "user.org.id",
      "value": "d94187fe-629c-4da8-804e-9dc82c1fb4b7"
    },
    {
      "key": "user.org.name",
      "value": "my_org"
    },
    {
      "key": "user.roles[i]",
      "value": "role_a"
    },
    {
      "key": "user.roles[0]",
      "value": "role_a"
    },
    {
      "key": "user.roles[i]",
      "value": "role_b"
    },
    {
      "key": "user.roles[1]",
      "value": "role_a"
    },
    {
      "key": "user.groups[i]",
      "value": "group_1"
    },
    {
      "key": "user.groups[0]",
      "value": "group_1"
    },
    {
      "key": "user.groups[i]",
      "value": "group_2"
    },
    {
      "key": "user.groups[1]",
      "value": "group_2"
    },
    {
      "key": "user.something.really.complex.nested[i]",
      "value": "here"
    },
    {
      "key": "user.something.really.complex.nested[0]",
      "value": "here"
    }
  ]
}
```

The reason a selector syntax was required was because the platform was reaching out directly to an idP or parsing claims on a JWT, but if there is a deterministic flattening, I believe we can get rid of that complexity.

1. If the platform owns the transformation layer in between platform and idP, the flattening algorithm can be exposed by the platform libs so that `otdfctl` can assist admins in knowing precisely what fields and values will be found for a Subject Context
2. if the platform owns the transformation layer between, admins could be given authorization to a platform endpoint to run the same transformation that happens in the lambda
3. if a platform consumer owns the deployed transformation, they have full control over fields and values and they just supply the endpoint to the platform in the config (meeting whatever interface contract is required)
4. configuring Entitlements (via Subject Sets -> Subject Mappings -> Attribute Values) goes back to the simplicity of field values and expected IN/NOT_IN values lists (rather than jq expressions expected to resolve to a value IN/NOT_IN a values list)
5. A case where all we have is a Subject Context and we need to find Entitlements is simplified because we can transform it to fields/values and look for the fields in the Policy DB instead of requiring knowledge of the jq selector expressions potentially applicable to that Subject Context (as those expressions are stored in the Subject Condition Sets of the DB at present).

**Comment by ttschampel** [comment]
I like the potential benefits of flattening the entity representation.  I do think the best home for that would be in a core built-in ; I don't think flattening would differ by external source.

This does raise the question on the most efficient way to get candidate subject sets for an entity and whether it should stay where it is now (retrieved before OPA call and provided as input) vs. other approaches like finding candidates after flattening, etc.

**Comment by jakedoublev** [comment]
@ttschampel 
> I do think the best home for that would be in a core built-in ; I don't think flattening would differ by external source.

This makes sense to me. As long as the flattening is deterministic, access stays deterministic, and impact of a Subject Set/Mapping change can be understood and communicated in advance.

> This does raise the question on the most efficient way to get candidate subject sets for an entity and whether it should stay where it is now (retrieved before OPA call and provided as input) vs. other approaches like finding candidates after flattening, etc.

I think there are probably two stories here with different needs, and this efficiency question is primarily focused on the first story (please correct me if I'm wrong): 
1. An Access Decision: this will always involve determining if a Subject is Entitled to the Resource Attributes on the data. Because of that, the decision logic will always take place when a) the Entity Representation is known (and deterministically flattenable in this case), and 2) the entity is entitled _specifically to the attributes on the data resource_. Because the data attributes are already known, we can always walk back up from data attributes to the subject, seeing if the mapped subject sets apply to that entity representation or not, and applying the boolean decision logic. We'll have any selector expressions or flattened fields from the data attributes already to determine access for the entity representation. This is the current state, and is still the future state (though with reduced complexity from flattening). [^1]
2. An admin story: what data is this subject entity entitled to? Only the Entity Representation (Subject Context) is known. With no data attributes, an admin or a platform function would need to identify the _potential _ selector expressions that could be found in subject sets mapped to attributes. I raised a form of this question in architecture hours last week but I think it is maybe still an unknown? This story would be solved by determinism of flattening because admins would be able to predict without question what is available to drive access upon within an entity representation.

[^1]: I think right now the [core decision function](https://github.com/opentdf/platform/blob/main/service/internal/access/pdp.go#L18-L26) is (oversimplified) `access(data attribute values, entity attribute values, attribute definitions) = true | false` but ideally it would be `access(entity representation, data attributes)` because we can determine if the entity is entitled to any individual data attributes in question _from the data attributes themselves (and their values and mapped subject sets)_. It shouldn't matter if they're entitled to other attributes, because we don't need those for a decision. An admin has different questions, hence the split admin story above.
