### ISSUE TITLE
Policy API: created_at & updated_at values are still null in response to entity creation request.

### ISSUE THREAD

**Issue by sievdokymov-virtru** [opentdf/platform#549]
Created_at and updated_at params are null in response for just created entity - e.g. namespace, attribute etc. 
Actual values are returned for further requests (Get/List etc).

**Steps to Reproduce**:
1. Run the backend server for the opened/platform (as described in the [Readme](https://github.com/opentdf/platform/blob/main/README.md)).
2. Create e.g. a namespace using NamespaceService.CreateNamespace gRPC request (0 OK is returned). 
3. Observe created_at and updated_at values in response metadata.

**Actual Result**:
_created_at_ and _updated_at_ timestamps are null in response:
<img width="1276" alt="null" src="https://github.com/opentdf/platform/assets/100794336/e86b067b-2e97-4c1c-a02a-eae418403300">

**Expected Result**:
_created_at_ and _updated_at_ timestamps are set properly during create/update operations and returned immediately in response.

Functionality is recently implemented in scope of https://github.com/opentdf/platform/issues/355

Correspondent JIRA issue: https://virtru.atlassian.net/browse/PLAT-3107

**Comment by jakedoublev** [comment]
This is expected behavior. However, it could be improved by either one of the following:
1. enhancing the [SQL create queries](https://github.com/opentdf/platform/blob/main/service/policy/db/attribute_values.go#L148) for policy objects and hydrating/responding with the returned values (the ideal path forward), or
2. by making a roundtrip `get` from the DB on the new row after `create` to respond back with the created values.

The first approach would be preferred to avoid extra roundtrips, though writes will always be far less frequent than reads, so performance isn't critical here.
