### ISSUE TITLE
Policy API: created_at & updated_at values have ‘seconds & nanos’ form which doesn’t provide clarity w/o transforming to date.

### ISSUE THREAD

**Issue by sievdokymov-virtru** [opentdf/platform#550]
created_at & updated_at metadata values are returned in ‘seconds & nanos’ form which isn’t really usable for user w/o additional transformation to suitable date value.

E.g. for the Get Namespace request:
<img width="1276" alt="Timestamps" src="https://github.com/opentdf/platform/assets/100794336/1d6eb949-0569-4cf6-9bdd-12d2814f4f66">

**Steps to Reproduce**:
1. Run the backend server for the opened/platform (as described in the [Readme](https://github.com/opentdf/platform/blob/main/README.md)).
2. Create e.g. a namespace using NamespaceService.CreateNamespace gRPC request with valid id (0 OK is returned). 
3. Get a namespace using NamespaceService.GetNamespace gRPC request. Observe created_at and updated_at values in response metadata.

**Actual Result**:
_created_at_ and _updated_at_ timestamps are in form of seconds and nanos which isn’t clear for a user:
<img width="1276" alt="Timestamps" src="https://github.com/opentdf/platform/assets/100794336/46fa429d-a4d1-4227-8117-3501dbf0f944">

**Expected Result**:
_created_at_ and _updated_at_ timestamps are transformed to date values to be usable and clear.

**Additional Info**:
Functionality is recently implemented in scope of https://github.com/opentdf/platform/issues/355

Correspondent JIRA issue: https://virtru.atlassian.net/browse/PLAT-3110

**Comment by jakedoublev** [comment]
Thanks for filing this issue!

These values come from the [proto definitions of the fields as timestamps](https://github.com/opentdf/platform/blob/main/service/common/common.proto#L10), where the timestamp is a [well known type](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto).

This standard allows conversion of the seconds or nanos to language-specific datetime constructs as [explained in the protos](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto#L43). Over the RESTful gateway, the values are transformed into JSON-standard timestamps, but not over gRPC.

<img width="983" alt="Screenshot 2024-04-10 at 11 04 22 AM" src="https://github.com/opentdf/platform/assets/83739412/c607262b-81ab-4d40-a794-0df4697c8f43">

This is the expected behavior of the protos.
