### ISSUE TITLE
Policy API: Wrong & missed info for parental namespace/attribute/attributeValue in response to GetAttribute/GetAttributeValue/GetMapping etc requests.

### ISSUE THREAD

**Issue by sievdokymov-virtru** [opentdf/platform#562]
Parental attribute & namespace info is mostly missed (names, fqn, active, metadata etc.) or even wrong (AttributeRule) in response to Get Attribute/GetAttributeValue/GetAttributeValuesByFqns etc requests.

Pls take a look at screenshots info.
E.g. pay attention to parental namespace info in response to GetAttribute call:
<img width="1279" alt="GetAttribute" src="https://github.com/opentdf/platform/assets/100794336/1bcd2f74-908d-48c5-ab11-fa6d18a177fe">

While valid Namespace info is present:
<img width="1274" alt="GetNamespace" src="https://github.com/opentdf/platform/assets/100794336/8a127521-5fe2-4570-b45c-26f2f2edcbf1">

Similar problem for parental namespace and attribute parameters during GetAttributeValue call:
<img width="1278" alt="GetAttributeValue" src="https://github.com/opentdf/platform/assets/100794336/b764082e-49e8-4a78-b25f-3c9cb26d754b">

Similar issue reproduces for Update requests, also affects responses for ResourceMappings, SubjectMappings services calls (AttributeValue info) etc.
 
**Expected Result**:
Presented response data contains valid values for parental entities

**Comment by jakedoublev** [comment]
Thanks for filing this issue! This is related to https://github.com/opentdf/platform/issues/366 

I think what you are seeing is a result of the behaviors of postman interpreting gRPC responses. In generated language code (at least Go), it is clear these values were not provided in response and that the fields are zero values (empty).

It is expected that many fields will be null/zero values because the graph relation is not expanded completely from each Policy Object. If an Attribute Definition is requested (`policy.attributes.AttributesService/GetAttribute`), it wouldn't make sense to provide back a bloated response like: 
1. the attribute's namespace
2. the attribute definition
3. the attribute's set of values
4. each attribute value's attribute definition
5. each attribute value's attribute definition's full set of values
6. each attribute value's attribute definition's namespace

The ATTRIBUTE_RULE_TYPE_ENUM_UNSPECIFIED is proto behavior to indicate the field was not provided, not a real rule type. The [proto definition for an attribute](https://github.com/opentdf/platform/blob/main/service/policy/attributes/attributes.proto#L60) requires the rule field to be specified on creation.

**Comment by sievdokymov-virtru** [comment]
@jakedoublev 
“ALL_OF” Rule was actually set during attribute creation (pls see correspondent value in GetAttribute response screen). So ‘UNSPECIFIED’ value appears really misleading. Is it expected as per your comment? Or should it be fixed? 

And thanks for insights.

**Comment by jakedoublev** [comment]
I agree that this would be misleading if it were not within the context of gRPC, when unspecified is the [default state](https://stackoverflow.com/questions/48833349/whats-the-purpose-of-having-default-enum-value-as-unspecified-in-google-proto) of every proto enum. If an enum value is not provided in a request or responses, that Message field (on any enum) will be unspecified per proto conventions. If you utilize the RESTful gateway, the confusion will go away because only actual values will be returned, for example:

```bash
# Attribute Value
grpcurl -plaintext -d '{"id":"0fd363db-27b1-4210-b77b-8c82fe044d41"}' localhost:8080 policy.attributes.AttributesService/GetAttributeValue
{
  "value": {
    "id": "0fd363db-27b1-4210-b77b-8c82fe044d41",
    "attribute": {
      "id": "e1536f25-d287-43ed-9ad9-2cf4a7698e5f"
    },
    "value": "value1",
    "fqn": "https://example.com/attr/attr2/value/value1",
    "active": true,
    "metadata": {
      "createdAt": "2024-04-12T19:45:52.511108Z",
      "updatedAt": "2024-04-12T19:45:52.511108Z"
    }
  }
}

# Attribute
grpcurl -plaintext -d '{"id":"e1536f25-d287-43ed-9ad9-2cf4a7698e5f"}' localhost:8080 policy.attributes.AttributesService/GetAttribute     
{
  "attribute": {
    "id": "e1536f25-d287-43ed-9ad9-2cf4a7698e5f",
    "namespace": {
      "id": "8f1d8839-2851-4bf4-8bf4-5243dbfe517d",
      "name": "example.com"
    },
    "name": "attr2",
    "rule": "ATTRIBUTE_RULE_TYPE_ENUM_ALL_OF",
    "values": [
      {
        "id": "0fd363db-27b1-4210-b77b-8c82fe044d41",
        "value": "value1",
        "active": true
      },
      {
        "id": "81f643f8-e050-4b97-a005-b61294d4c8bb",
        "value": "value2",
        "active": true
      }
    ],
    "fqn": "https://example.com/attr/attr2",
    "active": true,
    "metadata": {
      "createdAt": "2024-04-12T19:45:52.508505Z",
      "updatedAt": "2024-04-12T19:45:52.511108Z"
    }
  }
}
```

On a side note, it looks like the Postman settings around what data is rendered in a response, and possibly hiding zero/empty values if you'd like, [is configurable](https://github.com/postmanlabs/postman-app-support/issues/11278).
