### ISSUE TITLE
Enhance scoped DB logic to ensure that service / PEP developers can have separate or shared pools depending on the client and database connection

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#681]
The database experience in #647 led to some questions about resource pools and connections to the database. With the current implementation, it is possible to overwhelm the database by having too many connections since multiple clients will connect to the same database by default. It was determined that this was fine for the time being, but work needs to be done to ensure we can support more complex connections.

## Types of connections

- one client with a shared pool - a single client shared between services not scoped to specific clients
	- risk with policy data being mutated without the audit record by malicious PEPs
	- it reduces the complexity and resourcing
- many clients with a shared pool - clients scoped to specific schemas, but sharing a resource pool with one database server
	- reduced risk by enabling the limitation of schema access
	- less complexity than multiple databases or servers
- many clients with many database connections and/or database servers - clients scoped to separate databases with separate resource pools
	- low risk by limiting access based on database
	- more complexity and cost with maintaining servers
	- many databases on a single server is treated the same as many database servers

**Comment by jakedoublev** [comment]
After considering this further, I think we can simplify this to:

A service database connection = a schema, a client, and a dedicated pool.

> one client with a shared pool - a single client shared between services not scoped to specific clients
We do not support sharing pools among services due to complexity, resource allocation difficulty, service boundary confusion, and security of audit.

> many clients with a shared pool - clients scoped to specific schemas, but sharing a resource pool with one database server
Each service will maintain its own client within a dedicated pool. The policy service for example rolls up Attributes, Namespaces, Unsafe, Key Access Registrations, Resource Mappings, and Subject Mappings. Those services will all share a single pool allocated to the Policy service under the same schema and copies or references to the same client. The pool will manage connections of that client and any copies throughout the rolled up services. A theoretical PEP that needs a platform DB connection will have its own pool and client as registered, and its own schema tied to the service namespace. If multiple schemas are required by a PEP, it's an indication multiple services should be utilized instead with split pools and clients.

> many clients with many database connections and/or database servers - clients scoped to separate databases with separate resource pools
This is not supported. If multiple databases within one server or multiple database servers are required, this is not the responsibility of the platform to manage.

**Comment by jrschumacher** [comment]
I agree with your assessment. We can add the more complex solutions in the future if the community determines its need.
