### ISSUE TITLE
Client-Web error: Missing web-app client in quick start/howto guide

### ISSUE THREAD

**Issue by Vivekmauli14** [opentdf/platform#855]
Dear Community,

I was trying to setup the openTDF project on my development environment, after struggling a lot to setup this thing, I managed to bring this until here,

kindly help me suggest if I am doing anything wrong or the right steps to move further.

![Screenshot 2024-05-23 163016](https://github.com/opentdf/platform/assets/83024029/31675897-bc81-41a3-9868-13a57d690b05)

But as you can see here I am seeing client not found. and There is no way I am getting anything further from here. This is an deadend for me.
![Screenshot 2024-05-23 163309](https://github.com/opentdf/platform/assets/83024029/5aca09eb-3fa6-4a93-96db-bf26a59216ef)

Kindly help me to use this project in the full potential. Any kind of reference tutorial or updated documentation would be appreciated.
Thanks!

**Comment by dmihalcik-virtru** [comment]
It looks like it is failing due to a missing realm in keycloak. We may still have some holes in the documentation as we migrate to our newer backend. The failure here is likely due to some missing provisioning details in the configuration of the sample IdP. 

The current web-app demo requires adding a new client to the `opentdf` realm that the `service provision keycloak` command creates, as it needs a client that can do oauth2 via a frontend web application, while the ones that creates are for services.

The current script that does this is located here: https://github.com/opentdf/client-web/blob/main/.github/workflows/roundtrip/config-demo-idp.sh
