### ISSUE TITLE
Support per component logging configuration

### ISSUE THREAD

**Issue by ttschampel** [opentdf/platform#952]
It would be nice to support per component log levels (e.g. like [istio](https://istio.io/latest/docs/ops/diagnostic-tools/component-logging/)) so a user can target debug to specific areas of interest.

Also, a log format that contains the component would be more informative when reading/debugging the logs

**Comment by strantalis** [comment]
@ttschampel Part of this issue is solved but I don't think it has been fully rolled out yet. We are currently create a new child logger with the namespace name of the service. Maybe namespace should be changed to something else because we use that for policy as well. 

https://github.com/opentdf/platform/blob/main/service/pkg/server/services.go#L137

cc: @pbacon-blaber
